// <auto-generated />
using CRUDAspNetCoreMVC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDAspNetCoreMVC.Migrations
{
    [DbContext(typeof(CRUDContext))]
    [Migration("20200501161629_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUDAspNetCoreMVC.Models.Candidato", b =>
                {
                    b.Property<int>("CD_Candidato")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CH_Cidade")
                        .IsRequired();

                    b.Property<string>("CH_Email")
                        .IsRequired();

                    b.Property<string>("CH_Estado")
                        .IsRequired();

                    b.Property<string>("CH_Nome")
                        .IsRequired();

                    b.HasKey("CD_Candidato");

                    b.ToTable("Candidatos");
                });
#pragma warning restore 612, 618
        }
    }
}
